### ISSUE TITLE
the error with pubCrawl2

### ISSUE THREAD

**Issue by InfiniteSynthesis** [maximilianh/pubMunch#12]
Hello, when I use the tool pubCrawl2 to crawl files with thousands of pmids in pubmed, it often break down with the error:
ssl.sslError: read operation timed out

how can I solve it??
thanks

**Comment by maximilianh** [comment]
Sorry but I need to see the complete error message. There are many places
where this error could appera.

**Comment by InfiniteSynthesis** [comment]
The error message was like this:
Traceback (most recent call last):
  File "./pubCrawl2", line 193, in <module>
    main(args, options)
  File "./pubCrawl2", line 98, in main
    scrapeLib.crawlDocuments(docIds, skipIssns, options.forceContinue)
  File "/home/tcv/pubMunch/lib/pubCrawlLib.py", line 3457, in crawlDocuments
    paperData = crawlOneDoc(artMeta, srcDir)
  File "/home/tcv/pubMunch/lib/pubCrawlLib.py", line 3337, in crawlOneDoc
    crawlers, landingUrl = selectCrawlers(artMeta, srcDir)
  File "/home/tcv/pubMunch/lib/pubCrawlLib.py", line 3316, in selectCrawlers
    landingUrl = getLandingUrlSearchEngine(artMeta)
  File "/home/tcv/pubMunch/lib/pubCrawlLib.py", line 259, in getLandingUrlSearchEngine
    xrDoi = pubCrossRef.lookupDoi(articleData)
  File "/home/tcv/pubMunch/lib/pubCrossRef.py", line 42, in lookupDoi
    jsonStr = httpResp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)

what's more, I have to download many pmids. So I cut the list of pmids into pieces, and I opened several terminals to execute it at the same time. Does this affects or is there any other solution to accelerate the download?

**Comment by maximilianh** [comment]
This happens when it's trying to contact crossref to find the DOI of the article. It looks like crossref doesn't always reply at the moment. You could simply put a try: / except: around line 42 in pubCrossRef (this line: "jsonStr = httpResp.read()") and repeat the request if you get an "ssl.SSLError". Can you do that?

**Comment by maximilianh** [comment]
As for downlaoading many PMIDs, you can reduce the waiting time in pubCrawl2 (there is an option for it, I think it's -t). But be careful, as the publishers may block you at some point. May I ask what you're ultimately trying to do?

**Comment by InfiniteSynthesis** [comment]
I have sent you the pull request.
Now I have 12 terminals to execute the pubCrawl2 at the same time.
Before I make this change, all the terminals will break down after one night.
And now they are still running well.

However, I am not familiar with the json module (exactly I am not familiar with python as well)
So there may be some mistakes.

emmm, it took me a long time to test it. Sorry to reply so late.

**Comment by maximilianh** [comment]
This looks great, I've merged it. Let me know how your crawl goes.

On Sun, May 27, 2018 at 8:59 AM, InfiniteSynthesis <notifications@github.com
