### ISSUE TITLE
pubConvCrawler not working due to missing field

### ISSUE THREAD

**Issue by windweller** [maximilianh/pubMunch#18]
I git clone the latest repo and installed all the necessary dependencies.

Then I ran `pubCrawl2` without any terrible issue. 
And I did exactly what the README tells me to do:

```
mkdir myCrawl
echo 17695372 > myCrawl/pmids.txt
pubCrawl2 -du myCrawl
mkdir myCrawlText
pubConvCrawler myCrawl myCrawlText
```

Then I encountered this error...

```
INFO    -Creating directory myCrawlText/
INFO    -Looking for already converted files in /home/xx/pubMunch/myCrawlText
INFO    -could not find /home/xx/pubMunch/myCrawlText/updates.tab, this seems to be the first run in this dir
INFO    -Found 0 PMIDs that are already done
INFO    -Preparing cluster run, batchDir /home/xx/pubMunch/myCrawlText/clusterBatch, default type localhost, headNode ku.sdsc.edu
INFO    -Creating directory /home/xx/pubMunch/myCrawlText/build/jobfiles.tmp
INFO    -Directory myCrawl contains articleMeta.tab, treated as crawl directory
INFO    -Found metadata in myCrawl
missing fields: set(['pii', 'medlineCreatedDate', 'medlineCompletedDate', 'medlineRevisedDate', 'pmidVersion'])
Traceback (most recent call last):
  File "./pubConvCrawler", line 443, in <module>
    main(args)
  File "./pubConvCrawler", line 430, in main
    submitJobs(inDir, outDir, options.cluster, chunkSize, options.doImages)
  File "./pubConvCrawler", line 235, in submitJobs
    updateId, chunkSize, donePmids, tabExt)
  File "./pubConvCrawler", line 141, in splitCrawlerMeta
    assert False
AssertionError
```

Would really love if someone shares how to convert from PDF to text!

**Comment by maximilianh** [comment]
Yes, a student added these fields to the code for a particular purpose. I
have a vague memory that @rcurrie fixed this a long time ago, maybe the
change just is not in the current master branch? If not, it would be easy
to change the code to accept these new fields.

>

**Comment by windweller** [comment]
Hi Maximillian,

Thank you for the response and thanks for building this amazing library!
I fixed `lib/pubStore.py` (by changing the articleFields) and a few lines of unicode handling to get `pubConvCrawler` to run -- and it runs successfully now!

**Comment by windweller** [comment]
Also, for other people trying to use this tool

The link for:

Docx2text:
http://docx2txt.sourceforge.net/#code

Put this under `pubMunch/external` and PubMunch will call the perl script: `pubMunch/external/docx2txt-1.2/docx2txt.pl`

Also the link for
PDFBox, an Apache project. PubMunch uses an old version of this software (1.6.0) that can be found here: https://archive.apache.org/dist/pdfbox/1.6.0/

Download by `wget https://archive.apache.org/dist/pdfbox/1.6.0/pdfbox-app-1.6.0.jar` and put this under `pubMunch/external/` as well.

**Comment by maximilianh** [comment]
Hm, do you think I should distribute these tools with the pubMunch
software? That sounds like a good idea.

**Comment by rcurrie** [comment]
@windweller I have the master branch of this repo now running in production as it is. The tooling around it is at https://github.com/BRCAChallenge/pubMunch-BRCA. Its all dockerized but currently manually run step by step via the Makefile which shows how each tool is called.

**Comment by windweller** [comment]
@maximilianh Distributing these tools might cause legal trouble? The only thing I had to take care is PDFBox...which is a jar file that you need to download.

Maybe some links and reference in the README would be enough.

**Comment by windweller** [comment]
@rcurrie Hi Rob, that's really cool :) thanks for open-sourcing your code. I went through the Makefile and since I've already gotten PubMunch running -- I shouldn't need your docker version. It might be good if @maximilianh add your repo to the README though...might save other people a lot of trouble!

**Comment by maximilianh** [comment]
Hi Rob, hm, do you want to push your master into the main master? It seems
that there are still a few changes that haven't made it into my master
branch?

**Comment by rcurrie** [comment]
My master is [even](https://github.com/maximilianh/pubMunch/compare/master...rcurrie:master) with main master I believe. The Docker and other tooling are part of BRCA Exchange's somewhat specific use at the moment. I'm running master from your repo in production but the final matching back to BRCA variants is still in a separate repo. Once I have the docker full automated I can see about trying to integrate it with pubMunch/master.

**Comment by maximilianh** [comment]
Hm interesting, Allen said that he found the fixes in your repo...

**Comment by windweller** [comment]
My bad — I found the fix in Rob’s latest commit to the current master branch. I had the trouble because I was using a version of the PubMunch before his latest commit.

**Comment by maximilianh** [comment]
OK, great, nothing to do then!

>
